Repository nodeshift/centos7-s2i-nodejs, pull requests merged in 2018-04, with the labels that each got.

#75 build: update git to 2.9.3
  Dockerfile
  contrib/etc/install_node.sh
  s2i/run
Labels: in progress, review

#78 backport of commits from master to 8.x
  Dockerfile
  PUBLISHING.md
  contrib/etc/install_node.sh
  s2i/assemble
  s2i/run
  test/run.sh
  test/test-app/package-lock.json
  test/test-app/package.json
Labels: in progress, review

#81 feat: add RHEL7 image stream and application template
  imagestreams/nodejs-centos7.yml
  templates/nodejs-rest-http.json
Labels: in progress, review

#80 src: support 10.0.0
  versions.mk
Labels: in progress, review

#85 backport of commits from master (#77)
  Dockerfile
  PUBLISHING.md
  contrib/etc/install_node.sh
  s2i/assemble
  s2i/run
  test/run.sh
  test/test-app/package-lock.json
  test/test-app/package.json
Labels: in progress, review

#83 update 10.0.0 version to no-cr
  README.md
  versions.mk
Labels: in progress, review

#82 Merging of RHOAR and RHSCL into a single 'nodejs' imagestream
  imagestreams/nodejs-rhel7.json
Labels: in progress

#86 remove scl usage and link git instead
  Dockerfile
  contrib/etc/install_node.sh
  test/run.sh
  test/test-app/package.json
  test/test-app/server.js
Labels: review
