Repository nodeshift/centos7-s2i-nodejs, pull requests merged in 2018-10, with the labels that each got.

#141 build: add test for nss_wrapper
  test/.run.sh.swp
  test/run.sh
Labels: review

#144 feat: add npm build if 'build' script is present
  s2i/assemble
Labels: build, in progress, review

#145 build: remove debuginfo
  contrib/etc/install_node.sh
Labels: in progress, review

#148 OKD rebranding and sclorg move for centos7-s2i-nodejs
  README.md
  imagestreams/nodejs-centos7.json
  imagestreams/nodejs-rhel7.json
Labels: in progress

#150 chore: Improve the way a npm build script is found.
  s2i/assemble
Labels: in progress, review
