Repository nodeshift/centos7-s2i-nodejs, pull requests merged in 2018-03, with the labels that each got.

#42 test: add addon to test-app
  test/test-app/addon/binding.gyp
  test/test-app/addon/hello.cc
  test/test-app/greeting.ts
  test/test-app/package-lock.json
  test/test-app/package.json
Labels: review

#41 src: release Node.js version 8.10.0-cr
  Dockerfile
  contrib/etc/install_node.sh
  test/test-app/addon/binding.gyp
  test/test-app/addon/hello.cc
  test/test-app/greeting.ts
  test/test-app/package-lock.json
  test/test-app/package.json
  versions.mk
Labels: in progress, review

#44 test: add addon to test-app (#42)
  test/test-app/addon/binding.gyp
  test/test-app/addon/hello.cc
  test/test-app/greeting.ts
  test/test-app/package-lock.json
  test/test-app/package.json
Labels: in progress, review

#43 test: add addon to test-app (#42)
  test/test-app/addon/binding.gyp
  test/test-app/addon/hello.cc
  test/test-app/greeting.ts
  test/test-app/package-lock.json
  test/test-app/package.json
Labels: in progress, review

#45 src: use -cr suffix for candidate release image tags
  versions.mk
Labels: review

#47 src: update to Node.js 9.5.0
  contrib/etc/install_node.sh
  releases.json
  versions.mk
Labels: review

#46 chore: update to 8.10.0
  README.md
  releases.json
  versions.mk
Labels: review

#55 doc: replace versions info with link
  README.md
Labels: review

#54 build: add script to test and booster
  test/make-plus-booster-test.sh
Labels: in progress, review

#56 src: remove installation instructions for images
  README.md
  image-streams.centos7.json
Labels: in progress, review

#57 doc: remove outdated information
  PUBLISHING.md
Labels: in progress, review

#59 src: update to Node.js 9.9.0
  README.md
  releases.json
  test/.run.sh.swp
  versions.mk
Labels: in progress, review

#63 chore: update to 8.11.0
  README.md
  releases.json
  versions.mk
Labels: in progress, review

#62 src: update to Node.js 9.10.0
  README.md
  releases.json
  versions.mk
Labels: in progress, review

#66 doc: update publishing guide with latest steps
  PUBLISHING.md
Labels: docs, needs-review, review
