Repository nodeshift/centos7-s2i-nodejs, pull requests merged in 2018-08, with the labels that each got.

#120 chore: update to Node.js 10.8.0
  versions.mk
Labels: in progress, review

#121 test: add NPM_CONFIG_TARBALL check
  test/run.sh
Labels: review

#124 s2i: use fix-permssions script from s2i core image
  contrib/etc/install_node.sh
  s2i/assemble
Labels: in progress, review

#126 src: update node version to 8.11.4
  versions.mk
Labels: in progress, review

#127 src: update node version to 10.9.0
  versions.mk
Labels: in progress, review

#128 build: update versions to 8.11.4 and 10.9.0
  README.md
  versions.mk
Labels: in progress, review

#123 update imagestreams to registry.redhat.io
  imagestreams/nodejs-rhel7.json
Labels: in progress

#129 src: print node.js version
  s2i/run
Labels: in progress, review
