Repository nodeshift/centos7-s2i-nodejs, pull requests merged in 2018-05, with the labels that each got.

#87 src: support 10.1.0
  contrib/etc/install_node.sh
  versions.mk
Labels: in progress, review

#88 update 10.x version to 10.1.0
  README.md
  versions.mk
Labels: in progress, review

#91 update 8 version to 8.11.2
  README.md
Labels: in progress, review

#98 src: update centos7 imagestream to include latest
  imagestreams/nodejs-centos7.yml
  imagestreams/nodejs-rhel7.yml
Labels: enhancement, needs-review, review

#102 s2i: remove save-artifacts from assembly step
  s2i/assemble
Labels: in progress, review

#101 s2i: remove save-artifacts from assembly step
  s2i/assemble
Labels: needs-review

#100 s2i: remove save-artifacts from assembly step
  s2i/assemble
Labels: in progress, review

#99 s2i: remove save-artifacts from assembly step
  s2i/assemble
Labels: needs-review, review

#105 src: support 10.2.0
  versions.mk
Labels: in progress, review

#106 update 10 version to 10.2.1
  README.md
  versions.mk
Labels: in progress, review

#108 src: support for 10.3.0
  versions.mk
Labels: in progress, review
